[versions]

agp = "9.2.1"
compileSdk = "37"
targetSdk = "37"
minSdk = "23"

kotlin-lang = "2.4.0"
compose-multiplatform = "1.11.1"
compose-multiplatform-material3 = "1.9.0"
compose-multiplatform-materialIconsExtended = "1.7.3"
androidx-compose-runtime = "1.11.4"

kotlin-serialization = "1.11.0"
androidx-activityCompose = "1.13.0"
androidx-core = "1.19.0"

[libraries]

kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.8.0" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-lang" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-lang" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-appCompat = "androidx.appcompat:appcompat:1.7.1"
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-customView = { module = "androidx.customview:customview", version = "1.2.0" }
androidx-customViewPoolingContainer = { module = "androidx.customview:customview-poolingcontainer", version = "1.1.0" }
coil = { module = "io.coil-kt.coil3:coil-compose", version = "3.5.0" }
stately = { module = "co.touchlab:stately-concurrency", version = "2.1.0" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-animationGraphics = { module = "androidx.compose.animation:animation-graphics", version = "1.11.4" }
compose-bom = "androidx.compose:compose-bom:2026.06.01"
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material3 = "androidx.compose.material3:material3:1.4.0"
compose-materialRipple = { module = "androidx.compose.material:material-ripple" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-multiplatform-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-multiplatform-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-multiplatform-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-multiplatform-material3" }
compose-multiplatform-materialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-multiplatform-materialIconsExtended" }
compose-multiplatform-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-multiplatform-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-multiplatform-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.9.8" }
compose-navigation-multiplatform = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.9.2" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
compose-runtimeSaveable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "androidx-compose-runtime" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version = "1.11.4" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiUtil = { module = "androidx.compose.ui:ui-util", version = "1.11.4" }
vannitktech-mavenPublish-gradle = "com.vanniktech:gradle-maven-publish-plugin:0.37.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version = "1.1.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-lang" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-lang" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-lang" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-lang" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.37.0" }

[bundles]
